dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=pushi setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
git:
  submodules: false
deploy:
  provider: pypi
  user: joamag
  password:
    secure: ZIeojaBou+TLg11g+yMRE+lopAi1gkfXaBy6dKjXT20urFZd/lUL87su11OJq1QigJJ6XMkrOI3NMyGva1//eTYB/V2OdHER5BGV1HRUYvcOLl4gPccC4dLwqz2SG18pbh2Pj6aj2yTL3/Q7RWqGVvt2wpFEoM+s3NscLXkSj5k=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
