from typing import Any, Mapping, TypedDict

from .base import PushiRecord

class APN(PushiRecord):
    token: str
    event: str

class APNListing(TypedDict):
    subscriptions: list[APN]

class APNAPI(object):
    def list_apns(
        self, token: str | None = ..., event: str | None = ...
    ) -> APNListing: ...
    def create_apn(
        self, token: str, event: str, auth: str | None = ..., unsubscribe: bool = ...
    ) -> APN: ...
    def delete_apn(
        self, token: str, event: str, force: bool = ...
    ) -> Mapping[str, Any]: ...
    def delete_apns(self, token: str) -> Mapping[str, Any]: ...
    def subscribe_apn(self, *args, **kwargs) -> APN: ...
    def unsubscribe_apn(self, *args, **kwargs) -> Mapping[str, Any]: ...
