from typing import Any, Mapping, TypedDict

from .base import PushiRecord

class SMTP(PushiRecord):
    email: str
    event: str

class SMTPListing(TypedDict):
    subscriptions: list[SMTP]

class SMTPAPI(object):
    def list_smtps(
        self, email: str | None = ..., event: str | None = ...
    ) -> SMTPListing: ...
    def create_smtp(
        self, email: str, event: str, auth: str | None = ..., unsubscribe: bool = ...
    ) -> SMTP: ...
    def delete_smtp(
        self, email: str, event: str, force: bool = ...
    ) -> Mapping[str, Any]: ...
    def delete_smtps(self, email: str) -> Mapping[str, Any]: ...
    def subscribe_smtp(self, *args, **kwargs) -> SMTP: ...
    def unsubscribe_smtp(self, *args, **kwargs) -> Mapping[str, Any]: ...
