from typing import Any, Mapping

from .base import PushiRecord

class Web(PushiRecord):
    url: str
    event: str

class WebAPI(object):
    def create_web(
        self, url: str, event: str, auth: str | None = ..., unsubscribe: bool = ...
    ) -> Web: ...
    def delete_web(self, url: str, event: str) -> Mapping[str, Any]: ...
    def subscribe_web(self, *args, **kwargs) -> Web: ...
    def unsubscribe_web(self, *args, **kwargs) -> Mapping[str, Any]: ...
